site_name: Likelihood-Free Inference Documentation
# Configuration for MkDocs
# See: https://www.mkdocs.org/user-guide/configuration/
config:
    # The theme to use for the documentation
    theme: readthedocs
    # The name of the site
    name: Likelihood-Free Inference Documentation
    # The description of the site
    description: Experimenting with different likelihood-free inference methods
site_url: https://role-model.github.io/likelihood-free-inference/
nav:
    - Home: index.md
    - Version 2.x:
        - Getting Started: v2/getting-started.md
        - Types:
            - Comments: v2/types/comments.md
    - Version 1.x:
        - Types:
            - Comments: v1/types/comments.md
            - Posts: v1/types/posts.md


theme: readthedocs